const PERMISSIONS = [
  'vendor.approve',
  'vendor.reject',
  'vendor.view',
  'category.create',
  'category.update',
  'category.delete',
  'category.view',
  'service.create',
  'service.update',
  'service.delete',
  'service.publish',
  'service.suspend',
  'service.view.own',
  'offering.create',
  'offering.update',
  'offering.delete',
  'availability.update',
  'booking.create',
  'booking.confirm',
  'booking.reject',
  'booking.complete',
  'booking.cancel',
  'booking.reschedule',
  'booking.noshow',
  'booking.view.own',
  'booking.view.all',
  'booking.forceCancel',
  'payment.markCollected',
  'payment.webhook',
  'role.create',
  'role.view',
  'role.update',
  'role.assign',
];

module.exports = { PERMISSIONS };